version: "3.8"
services:
  frontend:
    container_name: GuessingGame-FE
    stdin_open: true
    build:
     context: ./frontend
     dockerfile: Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - "/app/node_modules"
     - "./frontend:/app"
  
  backend:
    container_name: GuessingGame-BE
    build:
     context: ./backend
     dockerfile: Dockerfile
    ports:
     - "8889:8080"
    restart: unless-stopped
